# -*- coding: utf-8 -*-
"""Image Generation Lab

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uzJhhuaX0oUDPt0lcXcSA4FuXzWq6_BN

# Setting Up Your Development Environment
"""

# Uninstall Colab's preinstalled modules which have dependency conflicts with
# the OpenAI Python library.
!pip uninstall tensorflow-probability -y
!pip uninstall llmx -y
# Install the OpenAI Python library.
!pip install --upgrade openai
# Install the requests library, which is useful for working with HTTP requests.
!pip install --upgrade requests

"""# Importing and Initializing OpenAI"""

import requests
from openai import OpenAI

client = OpenAI(api_key='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')

"""# Function to Download an Image from a Given URL"""

def download_image(filename, url):
    response = requests.get(url)
    if response.status_code == 200:
        with open(filename, 'wb') as file:
          file.write(response.content)
    else:
        print("Error downloading image from URL:", url)

"""# Function to Specify a Filename Based on the User Input"""

# Generates a file name from the user's input.
def filename_from_input(prompt):
    # Remove all non-alphanumeric characters from the prompt except spaces.
    alphanum = ""
    for character in prompt:
        if character.isalnum() or character == " ":
            alphanum += character
    # Split the alphanumeric prompt into words.
    # Take the first three words if there are more than three. Else, take all    of them.
    alphanumSplit = alphanum.split()
    if len(alphanumSplit) > 3:
        alphanumSplit = alphanumSplit[:3]
    # Join the words with underscores and return the result.
    return "images/" + "_".join(alphanumSplit)

"""# Function to Create an Image"""

# Create an image
# If model is not specified, the default is DALL-E-2.
def get_image(prompt, model="dall-e-2"):
    n = 2   # Number of images to generate
    image = client.images.generate(
        prompt=prompt,
        model=model,
        n=n,
        size="1024x1024"
    )

    # Download the image
    for i in range(n):
        filename = filename_from_input(prompt) + "_" + str(i+1) + ".png"
        download_image(filename, image.data[i].url)

    return image

"""# Using the Function with User Input"""

prompt = input("Enter a prompt: ")
response = get_image(prompt)
print(response)
# Feedback message
print("----------------------------------------------")
print("Image saved to", filename_from_input(prompt) + "_*.png!")

"""# Display Your Results"""

from IPython.display import Image, display

# Display the first image
display(Image(filename_from_input(prompt) + '_1.png'))

# Display the second image
display(Image(filename_from_input(prompt) + '_2.png'))

# If you have more images to display, copy the above and replace the numbers to represent the 3rd, 4th, and so on...